pipeline {
    agent any
    environment {
        // Use the pre-configured MAVEN_HOME environment variable
        MVN_HOME = '"C:\\Program Files\\apache-maven-3.8.5"'
    }
    stages {
        stage('git') {
            steps {
                git branch: 'main', credentialsId: '64338209-c2d5-4594-a04d-6672d7838d12', url: 'https://github.com/joel2500/JenkinsDemo.git'
            }
        }
        stage('Build with Maven') {
            steps {
             dir('my-app') {
                bat "${MVN_HOME}\\bin\\mvn clean install"
            }
        }
     }
       stage('Code-Analysis') {
            steps {
             dir('my-app') {
                bat "${MVN_HOME}\\bin\\mvn test"
            }
        }
     }     
  }
}