pipeline {
    agent any
    stages {
        stage('git') {
            steps {
                git branch: 'main', url: 'https://github.com/joel2500/JenkinsDemo.git'
            }
        }
        stage('Build with Maven') {
            steps {
              {
                sh "mvn clean install"
            }
        }
     }
       stage('Code-Analysis') {
            steps {
              {
                sh "mvn test"
            }
        }
     }     
  }
}