pipeline {
    agent any
    environment {
        // Use the pre-configured MAVEN_HOME environment variable
        MVN_HOME = '/opt/apache-maven-3.6.3'
    }
    stages {
        stage('git') {
            steps {
                git branch: 'main', url: 'https://github.com/joel2500/JenkinsDemo.git'
            }
        }
        stage('Code-Compile') {
            steps {
             dir('my-app') {
                sh "${MVN_HOME}/bin/mvn clean install"
            }
        }
     }
       stage('Code-Analysis') {
            steps {
             dir('my-app') {
                sh "${MVN_HOME}/bin/mvn test"
            }
        }
     }     
  }
}